// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260206185756_AddRegistrationFieldsToVehicle")]
    partial class AddRegistrationFieldsToVehicle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Backend.Models.CarMake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarMakes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 5,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Hyundai"
                        });
                });

            modelBuilder.Entity("Backend.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MakeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MakeId = 1,
                            Name = "Camry"
                        },
                        new
                        {
                            Id = 2,
                            MakeId = 1,
                            Name = "Corolla"
                        },
                        new
                        {
                            Id = 3,
                            MakeId = 1,
                            Name = "RAV4"
                        },
                        new
                        {
                            Id = 4,
                            MakeId = 1,
                            Name = "Highlander"
                        },
                        new
                        {
                            Id = 5,
                            MakeId = 1,
                            Name = "Prius"
                        },
                        new
                        {
                            Id = 6,
                            MakeId = 1,
                            Name = "Tacoma"
                        },
                        new
                        {
                            Id = 7,
                            MakeId = 1,
                            Name = "4Runner"
                        },
                        new
                        {
                            Id = 8,
                            MakeId = 2,
                            Name = "Civic"
                        },
                        new
                        {
                            Id = 9,
                            MakeId = 2,
                            Name = "Accord"
                        },
                        new
                        {
                            Id = 10,
                            MakeId = 2,
                            Name = "CR-V"
                        },
                        new
                        {
                            Id = 11,
                            MakeId = 2,
                            Name = "Pilot"
                        },
                        new
                        {
                            Id = 12,
                            MakeId = 2,
                            Name = "Odyssey"
                        },
                        new
                        {
                            Id = 13,
                            MakeId = 2,
                            Name = "HR-V"
                        },
                        new
                        {
                            Id = 14,
                            MakeId = 3,
                            Name = "F-150"
                        },
                        new
                        {
                            Id = 15,
                            MakeId = 3,
                            Name = "Mustang"
                        },
                        new
                        {
                            Id = 16,
                            MakeId = 3,
                            Name = "Explorer"
                        },
                        new
                        {
                            Id = 17,
                            MakeId = 3,
                            Name = "Escape"
                        },
                        new
                        {
                            Id = 18,
                            MakeId = 3,
                            Name = "Edge"
                        },
                        new
                        {
                            Id = 19,
                            MakeId = 3,
                            Name = "Bronco"
                        },
                        new
                        {
                            Id = 20,
                            MakeId = 4,
                            Name = "Silverado"
                        },
                        new
                        {
                            Id = 21,
                            MakeId = 4,
                            Name = "Equinox"
                        },
                        new
                        {
                            Id = 22,
                            MakeId = 4,
                            Name = "Malibu"
                        },
                        new
                        {
                            Id = 23,
                            MakeId = 4,
                            Name = "Traverse"
                        },
                        new
                        {
                            Id = 24,
                            MakeId = 4,
                            Name = "Tahoe"
                        },
                        new
                        {
                            Id = 25,
                            MakeId = 4,
                            Name = "Camaro"
                        },
                        new
                        {
                            Id = 26,
                            MakeId = 5,
                            Name = "3 Series"
                        },
                        new
                        {
                            Id = 27,
                            MakeId = 5,
                            Name = "5 Series"
                        },
                        new
                        {
                            Id = 28,
                            MakeId = 5,
                            Name = "X3"
                        },
                        new
                        {
                            Id = 29,
                            MakeId = 5,
                            Name = "X5"
                        },
                        new
                        {
                            Id = 30,
                            MakeId = 5,
                            Name = "X7"
                        },
                        new
                        {
                            Id = 31,
                            MakeId = 5,
                            Name = "M3"
                        },
                        new
                        {
                            Id = 32,
                            MakeId = 6,
                            Name = "C-Class"
                        },
                        new
                        {
                            Id = 33,
                            MakeId = 6,
                            Name = "E-Class"
                        },
                        new
                        {
                            Id = 34,
                            MakeId = 6,
                            Name = "GLC"
                        },
                        new
                        {
                            Id = 35,
                            MakeId = 6,
                            Name = "GLE"
                        },
                        new
                        {
                            Id = 36,
                            MakeId = 6,
                            Name = "S-Class"
                        },
                        new
                        {
                            Id = 37,
                            MakeId = 6,
                            Name = "GLA"
                        },
                        new
                        {
                            Id = 38,
                            MakeId = 7,
                            Name = "A4"
                        },
                        new
                        {
                            Id = 39,
                            MakeId = 7,
                            Name = "A6"
                        },
                        new
                        {
                            Id = 40,
                            MakeId = 7,
                            Name = "Q5"
                        },
                        new
                        {
                            Id = 41,
                            MakeId = 7,
                            Name = "Q7"
                        },
                        new
                        {
                            Id = 42,
                            MakeId = 7,
                            Name = "A3"
                        },
                        new
                        {
                            Id = 43,
                            MakeId = 7,
                            Name = "Q3"
                        },
                        new
                        {
                            Id = 44,
                            MakeId = 8,
                            Name = "Jetta"
                        },
                        new
                        {
                            Id = 45,
                            MakeId = 8,
                            Name = "Passat"
                        },
                        new
                        {
                            Id = 46,
                            MakeId = 8,
                            Name = "Tiguan"
                        },
                        new
                        {
                            Id = 47,
                            MakeId = 8,
                            Name = "Atlas"
                        },
                        new
                        {
                            Id = 48,
                            MakeId = 8,
                            Name = "Golf"
                        },
                        new
                        {
                            Id = 49,
                            MakeId = 8,
                            Name = "Taos"
                        },
                        new
                        {
                            Id = 50,
                            MakeId = 9,
                            Name = "Altima"
                        },
                        new
                        {
                            Id = 51,
                            MakeId = 9,
                            Name = "Sentra"
                        },
                        new
                        {
                            Id = 52,
                            MakeId = 9,
                            Name = "Rogue"
                        },
                        new
                        {
                            Id = 53,
                            MakeId = 9,
                            Name = "Pathfinder"
                        },
                        new
                        {
                            Id = 54,
                            MakeId = 9,
                            Name = "Murano"
                        },
                        new
                        {
                            Id = 55,
                            MakeId = 9,
                            Name = "Frontier"
                        },
                        new
                        {
                            Id = 56,
                            MakeId = 10,
                            Name = "Elantra"
                        },
                        new
                        {
                            Id = 57,
                            MakeId = 10,
                            Name = "Sonata"
                        },
                        new
                        {
                            Id = 58,
                            MakeId = 10,
                            Name = "Tucson"
                        },
                        new
                        {
                            Id = 59,
                            MakeId = 10,
                            Name = "Santa Fe"
                        },
                        new
                        {
                            Id = 60,
                            MakeId = 10,
                            Name = "Palisade"
                        },
                        new
                        {
                            Id = 61,
                            MakeId = 10,
                            Name = "Kona"
                        });
                });

            modelBuilder.Entity("Backend.Models.FuelRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FuelEfficiency")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("FuelType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GasStation")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("RefuelDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RefuelDate");

                    b.HasIndex("VehicleId");

                    b.ToTable("FuelRecords");
                });

            modelBuilder.Entity("Backend.Models.ServiceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MileageAtService")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextServiceDue")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NextServiceMileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiptUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceCenter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDate");

                    b.HasIndex("VehicleId");

                    b.ToTable("ServiceRecords");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentMileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EngineInfo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelType")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerAddress")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationDocumentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RegistrationExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RegistrationIssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegistrationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Seats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Transmission")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VIN")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate");

                    b.HasIndex("UserId");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Backend.Models.CarModel", b =>
                {
                    b.HasOne("Backend.Models.CarMake", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Make");
                });

            modelBuilder.Entity("Backend.Models.FuelRecord", b =>
                {
                    b.HasOne("Backend.Models.Vehicle", "Vehicle")
                        .WithMany("FuelRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Backend.Models.ServiceRecord", b =>
                {
                    b.HasOne("Backend.Models.Vehicle", "Vehicle")
                        .WithMany("ServiceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Backend.Models.Vehicle", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.CarMake", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Backend.Models.Vehicle", b =>
                {
                    b.Navigation("FuelRecords");

                    b.Navigation("ServiceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
